### ISSUE TITLE
North and south moon nodes

### ISSUE THREAD

**Issue by whitecolor** [mivion/ephemeris#11]
@mivion 
any advice how north and south moon nodes can be calculated?

**Comment by mivion** [comment]
This library provides calculations only for bodies.
To calc nodes of moon see [swisseph](https://github.com/mivion/swisseph).

**Comment by whitecolor** [comment]
Thanks for the reply. I'm interested in the solution that can be used on JS client-side. Is it possible to implement it in JS? What is needed for this?

**Comment by mivion** [comment]
May some one helps?

**Comment by whitecolor** [comment]
Is [this the place](https://github.com/mivion/swisseph/blob/3f14c8ac922b54222ee263f5b8ab935c6d2f2de9/deps/swisseph/sweph.c#L740) where algorithm can be taken from?

**Comment by 0xStarcat** [comment]
@whitecolor fwiw I found the formula for the Mean Ascending Node and Mean Perigee in a book titled `Astronomical Algorithims` by Jean Meeus and implemented them into my fork of this repo. Here's the commit and the implementation is in `src/utilities/luna.js` https://github.com/0xStarcat/Moshier-Ephemeris-JS/commit/1d3b02d8024d63f27e8532901a7581a417a282c5
