### ISSUE TITLE
Longitude speed

### ISSUE THREAD

**Issue by nastal** [mivion/ephemeris#12]
Cool script! Seeking a way to use it instead of swisseph for some simple calculations. Any ideas on how to add longitude speed and topocentric longitude(ecliptic) positions?

**Comment by SanjayPrabhakaran** [comment]
For Longitude speed, maybe you can use get the planet position for two different days and find the average speed. For topocentric, it will be difficult. have tried to mohier ephemeris on github maybe that may help you
