### ISSUE TITLE
How to find ascendant?

### ISSUE THREAD

**Issue by vrnico** [mivion/ephemeris#17]
Which data point is connected to the ascendant degree? I'm having trouble running my own calculations

**Comment by jeandav** [comment]
I'm wondering the same thing, have you by any chance found a solution yet?

**Comment by 0xStarcat** [comment]
For anyone who might find this issue - the ascendant is not in here. It requires a special calculation. The formula can be found in Meeus's book or https://en.wikipedia.org/wiki/Ascendant or in this example from one of my projects https://github.com/0xStarcat/CircularNatalHoroscopeJS/blob/master/src/utilities/astronomy.js#L93
