### ISSUE TITLE
Geocentric distance equal to -1?...

### ISSUE THREAD

**Issue by cptolemy** [mivion/ephemeris#7]
Hi,

I've just tested your code and noticed that apart from the moon the planet geocentric distances are always equal to -1.

Can you please tell me where the bug might be?

Kind regards,

CPtolemy

**Comment by mivion** [comment]
Hi,

Could anyone help in this?

**Comment by blucobalto** [comment]
Hi Mivion,
I created a pull request that solves (I hope) the problem of calculating the planetary geocentric distance.

Hello,
Blu

**Comment by cptolemy** [comment]
Hi Blu

Can you please provide a sample?

Kind regards

CPtolemy

**Comment by blucobalto** [comment]
Hi CPtolemy,
I sent the change (pull request) to Mivion that will have to accept it or not.
In an unofficial way you can test everything if you download the software from the fork:
https://github.com/blucobalto/ephemeris

The index.html file loads the exact values for the planetary geocentric distance (I hope).
The modified file is: planet.js

Kind regards,
Blu

**Comment by mivion** [comment]
Merged. Sorry for waiting.

**Comment by blucobalto** [comment]
No problem.
Thanks a lot,
Blu
