### ISSUE TITLE
local Apparent Sidereal Time Incorrect

### ISSUE THREAD

**Issue by smportal** [mivion/ephemeris#8]
In Meuss (2nd ed) Chapter 15, there is an example of rise/transit/set for Venus in Boston, MA. The test case below, with Meuss inputs is used to generate the local apparent sidereal time:

``
$processor.init();

$const.tlong = +71.0833;

$const.tlat = +42.3333;

$const.glat = +42.3333;

$const.height = 43.0;

$const.date = { day:20, month:3, year:1988, hours:0, minutes:0, seconds:0 };

$processor.calc($const.date,$moshier.body.venus);

last = $util.hms($moshier.body.venus.position.altaz.dLocalApparentSiderialTime);
``
From the above, last = 16h35m18s whereas Meuss calculates THETA0 = 11h50m58.1s (Meuss and the Astronomical Almanac 1988 agree.)

In addition, the following values in transit.js are not computed correctly:

``

$moshier.body.venus.position.altaz.transit.approxRiseUT = 26h56m22s (Moshier: 12h25m)

$moshier.body.venus.position.altaz.transit.approxLocalMeridian = 34h10m48s (Moshier: 19h41m)

$moshier.body.venus.position.altaz.transit.approxSetUT = 41h:26m13s (Moshier: 02h55m)

``

**Comment by mivion** [comment]
May the problem on time?
